/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/otp`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signIn`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signUp`; params?: Router.UnknownInputParams; } | { pathname: `/backend/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/backend/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/services/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/otp`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signIn`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signUp`; params?: Router.UnknownOutputParams; } | { pathname: `/backend/firebase`; params?: Router.UnknownOutputParams; } | { pathname: `/backend/firebaseConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/services/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/otp${`?${string}` | `#${string}` | ''}` | `/auth/signIn${`?${string}` | `#${string}` | ''}` | `/auth/signUp${`?${string}` | `#${string}` | ''}` | `/backend/firebase${`?${string}` | `#${string}` | ''}` | `/backend/firebaseConfig${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/otp`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signIn`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signUp`; params?: Router.UnknownInputParams; } | { pathname: `/backend/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/backend/firebaseConfig`; params?: Router.UnknownInputParams; } | `/services/${Router.SingleRoutePart<T>}` | { pathname: `/services/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
